### ISSUE TITLE
Site Format Breaks If Tab is Duplicated

### ISSUE THREAD

**Issue by TopiaryRabbit** [hkeward/marlos_website#10]
If you right-click the site's tab while in the Create Room page or an Edit Room page, the new tab has lost the site formatting. This issue does not happen if you duplicate a tab from any of the other pages (Like Home, About, Rooms).

Duplicate Tab from Create New Room
![Duplicate Tab from Create Room](https://user-images.githubusercontent.com/51684573/65478724-db585b80-de58-11e9-8151-7bce9d943d9c.png)

Duplicate Tab from Edit Room Page
![Duplicate Tab from Room Page](https://user-images.githubusercontent.com/51684573/65478739-e612f080-de58-11e9-8864-9d0ab146949d.png)

**Comment by hkeward** [comment]
This is due to the same issue causing #4.

All data is loaded into the website ONLY when visiting heatherward.dev. Directly accessing a URL does not trigger a request to the server and should.

**Comment by hkeward** [comment]
Fixed with #11
